### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by YH126** [JoloTolentino/SEERV2#1]
**When I execute the server-main.py file, it appear **

File "server-main.py", line 10, in <module>
    from DepthEstimator import DepthEstimator
  File "/Users/yh/Python/Seer_V-2-main/modules/DepthEstimator.py", line 9, in <module>
    from git import Blob
ModuleNotFoundError: No module named 'git'

**and  execute the client-main.py file, it appear **

Traceback (most recent call last):
  File "client-main.py", line 13, in <module>
    from UDP_Client import client 
ModuleNotFoundError: No module named 'UDP_Client'

**Comment by JoloTolentino** [comment]
comment out the imported module, the library import was on accident and will work once you configure the project using config.py
